# fly.toml app configuration file generated for spring-ecommerce-test on 2023-06-08T18:02:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-ecommerce-test"
primary_region = "eze"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
