# fly.toml app configuration file generated for spring-ecommerce on 2023-06-11T11:18:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-ecommerce"
primary_region = "eze"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
