# fly.toml app configuration file generated for app-ecommerce on 2023-06-03T17:10:35-03:00
#
# See https://fly.io/docs/reference/confguration/ for information about how to use this file.
#

app = "app-ecommerce"
primary_region = "eze"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
